### ISSUE TITLE
Doubt with#2-compare-weights.ipynb

### ISSUE THREAD

**Issue by ayubih** [ariG23498/keras-nlp-hugging-face-integration#1]
I was wondering if you could explain how did you decide on comparing weights in [compare_weights](https://github.com/ariG23498/keras-nlp-hugging-face-integration/blob/main/%232-compare-weights.ipynb) specifically how the layers are being fetched for comparison. Are you looking at `keras_backbone.summary()` to get the layers or something else like [model.safetensors.index.json](https://huggingface.co/google/paligemma-3b-pt-224/blob/main/model.safetensors.index.json)? Thank you!

**Comment by ariG23498** [comment]
Hey @hsuyab thank you for your interest in the work.

> Are you looking at keras_backbone.summary() to get the layers or something else like [model.safetensors.index.json](https://huggingface.co/google/paligemma-3b-pt-224/blob/main/model.safetensors.index.json)?

That is exactly right. You would need to first understand the architecture and the name of the layers, after that it should be fairly easy to map them.

**Comment by ayubih** [comment]
Thank you for the detailed explanation! I hope I can get it working to make my first os contribution. 
Also, a quick question to inspect the keras_backbone the `.summary()` does not show the `image_encoder` in their but you used that as well. I think that is inside the `pali_gemma_vit` layer, right? 
If that's true then I should be going through each layer in the `summary()` output. Would that be correct?

**Comment by ariG23498** [comment]
> If that's true then I should be going through each layer in the summary() output. Would that be correct?

Yes. I suggest you first look at the summary of the `causal lm model`. Then dive into each components.

**Comment by ariG23498** [comment]
Is it okay to close this issue? Also, all the very best on your first contribution to the Keras-NLP repository.

**Comment by ayubih** [comment]
My bad, I will close it. Thank you!
